shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.show_cart, name='cart'),
    path('detail/', views.CartDetail.as_view(), name='cart_api'),
    path('add/<int:product_id>/', views.AddCartItemView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', views.CartRemoveItemView.as_view(), name='cart_remove'),
    path('checkout/', views.show_checkout, name='checkout'),
    path('final/', views.OrderAPIView.as_view(), name='final'),
    path('paid/', views.CheckOut.as_view(), name='paid')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('orders.urls')),
    path('', include('productions.urls', namespace='productions')),
    path('accounts/', include('customers.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/orders/models.py
import uuid

from django.db import models
from productions.models import Product
from customers.models import User
from core.models import BaseModel
from django.utils.translation import gettext_lazy as _

# Create your models here.


class Address(models.Model):
    state = models.CharField(_("استان"), max_length=100)
    city = models.CharField(_("شهر"), max_length=100)
    street = models.CharField(_("خیابان"), max_length=100)
    user_id = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name=_("کاربر"))

    class Meta:
        verbose_name = _('آدرس')
        verbose_name_plural = _('آدرس ها')

    def __str__(self):
        # return str(self.user_id)
        return f"{self.city}-{self.street}"


class Order(BaseModel):
    address_id = models.ForeignKey(Address, on_delete=models.CASCADE, verbose_name=_("آدرس"))
    paid = models.BooleanField(verbose_name=_("پرداخت شده"), default=False)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("کاربر"))

    class Meta:
        verbose_name = _('سفارش')
        verbose_name_plural = _('سفارش ها')

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class Cart(models.Model):
    identifier = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)

    def add_item(self, product, quantity=0):
        cart_item, created = OrderItem.objects.get_or_create(cart=self, product_id=product, price=product.price)
        cart_item.quantity += quantity
        cart_item.save()

    def remove_item(self, product):
        try:
            cart_item = OrderItem.objects.get(cart=self, product_id=product)
            cart_item.delete()
        except OrderItem.DoesNotExist:
            pass

    def get_total_quantity(self):
        return self.cartitem_set.aggregate(total_quantity=models.Sum('quantity'))['total_quantity'] or 0

    def get_total_price(self):
        return self.cartitem_set.annotate(total_price=models.F('quantity') * models.F('product__price')) \
            .aggregate(total_price=models.Sum('total_price'))['total_price'] or 0

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='order_items', on_delete=models.CASCADE, verbose_name=_("مربوط به سفارش"), null=True, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name=_("محصول"))
    price = models.PositiveIntegerField(_("قیمت"))
    quantity = models.PositiveIntegerField(_("تعداد"), default=0)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = _('آیتم سفارش')
        verbose_name_plural = _('آیتم های سفارش')

    def get_cost(self):
        return self.quantity * self.price

shop/orders/forms.py
from django import forms
from .models import Order, Address

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 51)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='تعداد')


class OrderForm(forms.Form):
    address = forms.ModelChoiceField(queryset=Address.objects.none(), label='آدرس')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(OrderForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['address'].queryset = Address.objects.filter(user_id=user.id)

shop/orders/views.py
import uuid

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from .forms import CartAddProductForm, OrderForm
from productions.models import Product
from .models import Cart, OrderItem, Order, Address
from .serializer import CartSerializer, OrderItemSerializer, OrderDetailSerializer
from django.conf import settings


# Create your views here.


class AddCartItemView(APIView):

    def post(self, request, product_id):
        cart_identifier = request.COOKIES.get('cart_identifier')
        if not cart_identifier:
            cart_identifier = str(uuid.uuid4())
        product = get_object_or_404(Product, id=product_id)
        form = CartAddProductForm(request.POST)
        cart_tuple = Cart.objects.get_or_create(identifier=cart_identifier)
        cart = cart_tuple[0]
        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            cart.add_item(product, quantity)
            cart_serializer = CartSerializer(cart)
            response = Response(cart_serializer.data, status=status.HTTP_200_OK)
            response.set_cookie(settings.CART_COOKIE_NAME, cart_serializer.data)
            response.set_cookie('cart_identifier', cart_identifier)
            return response


class CartRemoveItemView(APIView):

    def post(self, request, product_id):
        cart_identifier = request.COOKIES.get('cart_identifier')
        if not cart_identifier:
            cart_identifier = str(uuid.uuid4())
        cart = Cart.objects.get_or_create(identifier=cart_identifier)
        cart = cart[0]
        product = get_object_or_404(Product, id=product_id)
        cart.remove_item(product)
        response = Response(status=200)
        response.set_cookie(settings.CART_COOKIE_NAME, '')
        return response


class CartDetail(APIView):
    """
        Detail of Cart
    """

    serializer_class = CartSerializer

    def get(self, request):
        cart_identifier = request.COOKIES.get('cart_identifier')
        if not cart_identifier:
            cart_identifier = str(uuid.uuid4())
        cart, _ = Cart.objects.get_or_create(identifier=cart_identifier)
        serializer = CartSerializer(cart)
        response = Response(serializer.data)
        response.set_cookie('cart_identifier', cart_identifier)
        return response


def show_cart(request):
    return render(request, 'cart.html', {})


# SHOW CHECKOUT HTML
def show_checkout(request):
    if request.user.is_authenticated:
        form = OrderForm(request.POST or None, user=request.user)
        return render(request, 'checkout.html', {'form': form})
    else:
        return HttpResponse('ابتدا وارد شوید')


#  ADD ORDER in DATABASE
class OrderAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        address_id = request.data.get('address')
        address = Address.objects.get(pk=address_id)
        order = Order.objects.create(address_id=address, user_id=request.user)
        serializer = OrderDetailSerializer(order)
        cart_identifier = request.COOKIES.get('cart_identifier')
        cart = Cart.objects.get(identifier=cart_identifier)
        order_items = OrderItem.objects.filter(cart=cart)
        for item in order_items:
            item.order = order
            item.save()
        response = Response(serializer.data)
        response.delete_cookie('mycart')
        response.delete_cookie('cart_identifier')
        return response


# PAID ORDER
class CheckOut(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        order = Order.objects.filter(user_id=request.user).order_by('id').last()
        order.paid = True
        order.save()
        return Response()


class OrderDetail(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, order_id):
        order = Order.objects.get(pk=order_id)
        serializer = OrderDetailSerializer(order)
        return Response(serializer.data)


class OrderDetailInfo(APIView):
    def get(self, request):
        html = render(request, 'order_detail.html')
        return Response({'html': html.content})

shop/orders/templates/cart.html
{% extends 'base.html' %}

{% block content %}
    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table id="cart-table" class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>نام محصول</th>
                            <th>قیمت</th>
                            <th>تعداد</th>
                            <th>مجموع</th>
                            <th>حذف</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">

                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" action="">
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" placeholder="کد تخفیف">
                        <div class="input-group-append">
                            <button class="btn btn-primary">تایید کد</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">سبد خرید</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>جمع محصولات</h6>
                            <h6 class="total-sum">$150</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">هزینه ارسال</h6>
                            <h6 id="send" class="font-weight-medium">$10</h6>
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>مجموع</h5>
                            <h5 id="final"></h5>
                        </div>
                        <a href="{% url 'orders:checkout' %}"><button class="btn btn-block btn-primary font-weight-bold my-3 py-3">نهایی کردن خرید</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->
<script>
$(document).ready(function() {
  $.ajax({
    url: '{% url "orders:cart_api" %}',
    type: 'GET',
    dataType: 'json',
    success: function(data) {
      // console.log(data.cartitem_set)
      var cartItems = data.cartitem_set;
      var tableBody = $('#cart-table tbody');
      var totalSum = 0;

      $.each(cartItems, function(index, item) {
        var productName = item.product_id.name;
        // var productImage = item.product_id.main_image;
        console.log((productName))
        var itemPrice = item.price;
        console.log((itemPrice))
        var itemQuantity = item.quantity;
        var itemTotal = itemPrice * itemQuantity;

        var row = $('<tr>').data('product-id', item.product_id.id);
        var productCell = $('<td>').addClass('align-middle').attr('id', 'product-name').html('<img src="" alt="" style="width: 50px;"> ' + productName);
        var priceCell = $('<td>').addClass('align-middle').attr('id', 'item-price').text(itemPrice);
        var quantityCell = $('<td>').addClass('align-middle').attr('id', 'item-quantity').text(itemQuantity);
        // var quantityCell = $('<td>').addClass('align-middle').html('<div class="input-group quantity mx-auto" style="width: 100px;"><form action="" method="POST">{% csrf_token %}' + item.update_quantity_form.quantity + item.update_quantity_form.override + '<input class="btn btn-primary" type="submit" value="به روزرسانی"></form></div>' + itemQuantity);
        var totalCell = $('<td>').addClass('align-middle').text(itemTotal);
        var removeCell = $('<td>').addClass('align-middle').html('<button class="btn btn-sm btn-danger" id="remove-item"><i class="fa fa-times"></i></button>');

        $(document).on('click', '#remove-item', function() {
            // var productId = item.product_id.id;
            var productId = $(this).closest('tr').data('product-id');

            $.ajax({
                url: '/cart/remove/' + productId + '/',
                type: 'POST',
                success: function(data) {
                    console.log('Item removed from cart');
                    window.location.href = '{% url "orders:cart" %}'
                },
            });
        });
        totalSum += itemTotal;


        row.append(productCell, priceCell, quantityCell, totalCell, removeCell);
        tableBody.append(row);
      });
      $('.total-sum').text('تومان' + totalSum);
      var send = 25000;
      var final = send + totalSum;
      $('#send').text('تومان' + send);
      $('#final').text('تومان' + final);


    },
  });
});
  function getCookie(name) {
  var cookieName = name + "=";
  var cookieArray = document.cookie.split(";");
  for (var i = 0; i < cookieArray.length; i++) {
    var cookie = cookieArray[i];
    while (cookie.charAt(0) === " ") {
      cookie = cookie.substring(1, cookie.length);
    }
    if (cookie.indexOf(cookieName) === 0) {
      return cookie.substring(cookieName.length, cookie.length);
    }
  }
  return null;
}
</script>

{% endblock content %}

shop/orders/templates/checkout.html
{% extends 'base.html' %}

{% block content %}
    <!-- Checkout Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">آدرس و مشخصات تحویل</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="row">
                        <form id="address-form" method="POST">
                            {% csrf_token %}
                            <div class="col-md-6 form-group">
                                {{form.as_p}}
                                <input type="submit" value="تایید آدرس">
                            </div>
                        </form>
                        <div class="col-md-12">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="shipto">
                                <label class="custom-control-label" for="shipto"  data-toggle="collapse" data-target="#shipping-address">اضافه کردن آدرس جدید</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="collapse mb-5" id="shipping-address">
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">آدرس جدید</span></h5>
                    <div class="bg-light p-30">
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <label>استان</label>
                                <input class="form-control" type="text" placeholder="John">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>شهر</label>
                                <input class="form-control" type="text" placeholder="Doe">
                            </div>
                            <div class="col-md-6 form-group">
                                <label>خیابان</label>
                                <input class="form-control" type="text" placeholder="example@email.com">
                            </div>
                            <button class="btn btn-block btn-primary font-weight-bold py-3">اضافه کردن</button>
                        </div>
                    </div>
                </div>
            </div>

                <div class="mb-5">
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">روش پرداخت</span></h5>
                    <div class="bg-light p-30">
                        <div class="form-group">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="paypal">
                                <label class="custom-control-label" for="paypal">Paypal</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="directcheck">
                                <label class="custom-control-label" for="directcheck">Direct Check</label>
                            </div>
                        </div>
                        <div class="form-group mb-4">
                            <div class="custom-control custom-radio">
                                <input type="radio" class="custom-control-input" name="payment" id="banktransfer">
                                <label class="custom-control-label" for="banktransfer">Bank Transfer</label>
                            </div>
                        </div>
                        <button id="paid" class="btn btn-block btn-primary font-weight-bold py-3">نهایی کردن سفارش</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Checkout End -->

<script>
    $(document).ready(function () {

        $('#address-form').submit(function (event) {
            event.preventDefault();

            var formData = $(this).serialize();
            var token = getCookie('access_token');

            $.ajaxSetup({
                headers: {
                    Authorization: 'Bearer ' + token
                }
            });
            $.ajax({
                url: '{% url "orders:final" %}',
                type: 'POST',
                data: formData,
                success: function (response) {
                    alert('آدرس انتخاب شد')
                },
            });
        });
        $("#paid").click(function() {
            var token = getCookie('access_token');
            console.log(token);
            $.ajaxSetup({
                headers: {
                    Authorization: 'Bearer ' + token
                }
            });
            $.ajax({
                url: "{% url 'orders:paid' %}",
                type: "POST",
                success: function(data) {
                    // window.location.href = "{% url 'orders:paid' %}";
                    alert('پرداخت انجام شد')
                },
            });
        });
    });




    function getCookie(name) {
        var cookieName = name + "=";
        var cookieArray = document.cookie.split(";");
        for (var i = 0; i < cookieArray.length; i++) {
          var cookie = cookieArray[i];
          while (cookie.charAt(0) === " ") {
            cookie = cookie.substring(1, cookie.length);
          }
          if (cookie.indexOf(cookieName) === 0) {
            return cookie.substring(cookieName.length, cookie.length);
          }
        }
        return null;
    }
</script>
{% endblock content %}