shop/customers/urls.py
from django.urls import path
from . import api
from . import views

app_name = 'customers'

urlpatterns = [
      path('edit/profile/', views.show_profile, name='edit_profile'),
      path('load/', views.ProfileInfo.as_view(), name='load'),
      path('profile/', api.Profile.as_view(), name='profile'),
      path('api/login/', api.LoginAPIView.as_view(), name='login'),
      path('login-simple/', views.LoginSimple.as_view(), name='login_simple'),
      path('login-otp/', api.LoginOtp.as_view(), name='login_otp'),
      path('verification/', api.Verification.as_view(), name='verification'),
      path('api/register/', api.RegisterApi.as_view(), name="register"),
      path('logout/', api.Logout.as_view(), name='logout'),
      path('address/', api.AddressApi.as_view(), name='address'),
      path('address-info/', views.AddressInfo.as_view(), name='address_info'),
      path('order/', api.OrderAPI.as_view(), name='order'),
      path('order-info/', views.OrderInfo.as_view(), name='order_info'),
      path('order/<int:pk>/', api.OrderDetail.as_view(), name='order_detail'),
      path('order-detail/', views.OrderDetailInfo.as_view(), name='order_detail_info'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.show_cart, name='cart'),
    path('detail/', views.CartDetail.as_view(), name='cart_api'),
    path('add/<int:product_id>/', views.AddCartItemView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', views.CartRemoveItemView.as_view(), name='cart_remove'),
    path('checkout/', views.show_checkout, name='checkout'),
    path('final/', views.OrderAPIView.as_view(), name='final'),
    path('paid/', views.CheckOut.as_view(), name='paid')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('orders.urls')),
    path('', include('productions.urls', namespace='productions')),
    path('accounts/', include('customers.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/customers/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .manager import MyUserManager
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin


# Create your models here.

class User(AbstractBaseUser, PermissionsMixin):
    fullname = models.CharField(null=True, max_length=100)
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
    )
    phone = models.CharField(max_length=100, unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = _('کاربر')
        verbose_name_plural = _('کاربران')

    USERNAME_FIELD = "phone"
    REQUIRED_FIELDS = []
    objects = MyUserManager()

    def __str__(self):
        return self.phone

shop/orders/models.py
import uuid

from django.db import models
from productions.models import Product
from customers.models import User
from core.models import BaseModel
from django.utils.translation import gettext_lazy as _

# Create your models here.


class Address(models.Model):
    state = models.CharField(_("استان"), max_length=100)
    city = models.CharField(_("شهر"), max_length=100)
    street = models.CharField(_("خیابان"), max_length=100)
    user_id = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, verbose_name=_("کاربر"))

    class Meta:
        verbose_name = _('آدرس')
        verbose_name_plural = _('آدرس ها')

    def __str__(self):
        # return str(self.user_id)
        return f"{self.city}-{self.street}"


class Order(BaseModel):
    address_id = models.ForeignKey(Address, on_delete=models.CASCADE, verbose_name=_("آدرس"))
    paid = models.BooleanField(verbose_name=_("پرداخت شده"), default=False)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("کاربر"))

    class Meta:
        verbose_name = _('سفارش')
        verbose_name_plural = _('سفارش ها')

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class Cart(models.Model):
    identifier = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)

    def add_item(self, product, quantity=0):
        cart_item, created = OrderItem.objects.get_or_create(cart=self, product_id=product, price=product.price)
        cart_item.quantity += quantity
        cart_item.save()

    def remove_item(self, product):
        try:
            cart_item = OrderItem.objects.get(cart=self, product_id=product)
            cart_item.delete()
        except OrderItem.DoesNotExist:
            pass

    def get_total_quantity(self):
        return self.cartitem_set.aggregate(total_quantity=models.Sum('quantity'))['total_quantity'] or 0

    def get_total_price(self):
        return self.cartitem_set.annotate(total_price=models.F('quantity') * models.F('product__price')) \
            .aggregate(total_price=models.Sum('total_price'))['total_price'] or 0

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='order_items', on_delete=models.CASCADE, verbose_name=_("مربوط به سفارش"), null=True, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name=_("محصول"))
    price = models.PositiveIntegerField(_("قیمت"))
    quantity = models.PositiveIntegerField(_("تعداد"), default=0)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = _('آیتم سفارش')
        verbose_name_plural = _('آیتم های سفارش')

    def get_cost(self):
        return self.quantity * self.price

shop/orders/forms.py
from django import forms
from .models import Order, Address

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 51)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='تعداد')


class OrderForm(forms.Form):
    address = forms.ModelChoiceField(queryset=Address.objects.none(), label='آدرس')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(OrderForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['address'].queryset = Address.objects.filter(user_id=user.id)

shop/customers/views.py
import jwt
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.utils import timezone
from django.views import View
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import User
from django.conf import settings


class LoginSimple(APIView):
    def get(self, request):
        html = render(request, 'login_simple.html')
        return Response({'html': html.content})


def show_profile(request):
    try:
        token = request.COOKIES.get('access_token')
        decoded_token = jwt.decode(token, settings.SECRET_KEY, algorithms=['HS256'])
        current_time = timezone.now().timestamp()
        if request.user.is_authenticated and current_time < decoded_token['exp']:
            return render(request, 'profile.html', context={})
        else:
            return HttpResponse('ابتدا وارد شوید')
    except Exception:
        return HttpResponse('ابتدا وارد شوید')


class ProfileInfo(APIView):
    def get(self, request):
        html = render(request, 'edit_prof.html')
        return Response({'html': html.content})


class AddressInfo(APIView):
    def get(self, request):
        html = render(request, 'address.html')
        return Response({'html': html.content})


class OrderInfo(APIView):
    def get(self, request):
        html = render(request, 'order.html')
        return Response({'html': html.content})


class OrderDetailInfo(APIView):
    def get(self, request):
        html = render(request, 'order_detail.html')
        return Response({'html': html.content})

shop/orders/views.py
import uuid

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from .forms import CartAddProductForm, OrderForm
from productions.models import Product
from .models import Cart, OrderItem, Order, Address
from .serializer import CartSerializer, OrderItemSerializer, OrderDetailSerializer
from django.conf import settings


# Create your views here.


class AddCartItemView(APIView):

    def post(self, request, product_id):
        cart_identifier = request.COOKIES.get('cart_identifier')
        if not cart_identifier:
            cart_identifier = str(uuid.uuid4())
        product = get_object_or_404(Product, id=product_id)
        form = CartAddProductForm(request.POST)
        cart_tuple = Cart.objects.get_or_create(identifier=cart_identifier)
        cart = cart_tuple[0]
        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            cart.add_item(product, quantity)
            cart_serializer = CartSerializer(cart)
            response = Response(cart_serializer.data, status=status.HTTP_200_OK)
            response.set_cookie(settings.CART_COOKIE_NAME, cart_serializer.data)
            response.set_cookie('cart_identifier', cart_identifier)
            return response


class CartRemoveItemView(APIView):

    def post(self, request, product_id):
        cart_identifier = request.COOKIES.get('cart_identifier')
        if not cart_identifier:
            cart_identifier = str(uuid.uuid4())
        cart = Cart.objects.get_or_create(identifier=cart_identifier)
        cart = cart[0]
        product = get_object_or_404(Product, id=product_id)
        cart.remove_item(product)
        response = Response(status=200)
        response.set_cookie(settings.CART_COOKIE_NAME, '')
        return response


class CartDetail(APIView):
    """
        Detail of Cart
    """

    serializer_class = CartSerializer

    def get(self, request):
        cart_identifier = request.COOKIES.get('cart_identifier')
        if not cart_identifier:
            cart_identifier = str(uuid.uuid4())
        cart, _ = Cart.objects.get_or_create(identifier=cart_identifier)
        serializer = CartSerializer(cart)
        response = Response(serializer.data)
        response.set_cookie('cart_identifier', cart_identifier)
        return response


def show_cart(request):
    return render(request, 'cart.html', {})


# SHOW CHECKOUT HTML
def show_checkout(request):
    if request.user.is_authenticated:
        form = OrderForm(request.POST or None, user=request.user)
        return render(request, 'checkout.html', {'form': form})
    else:
        return HttpResponse('ابتدا وارد شوید')


#  ADD ORDER in DATABASE
class OrderAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        address_id = request.data.get('address')
        address = Address.objects.get(pk=address_id)
        order = Order.objects.create(address_id=address, user_id=request.user)
        serializer = OrderDetailSerializer(order)
        cart_identifier = request.COOKIES.get('cart_identifier')
        cart = Cart.objects.get(identifier=cart_identifier)
        order_items = OrderItem.objects.filter(cart=cart)
        for item in order_items:
            item.order = order
            item.save()
        response = Response(serializer.data)
        response.delete_cookie('mycart')
        response.delete_cookie('cart_identifier')
        return response


# PAID ORDER
class CheckOut(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        order = Order.objects.filter(user_id=request.user).order_by('id').last()
        order.paid = True
        order.save()
        return Response()


class OrderDetail(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, order_id):
        order = Order.objects.get(pk=order_id)
        serializer = OrderDetailSerializer(order)
        return Response(serializer.data)


class OrderDetailInfo(APIView):
    def get(self, request):
        html = render(request, 'order_detail.html')
        return Response({'html': html.content})

shop/customers/templates/address.html
<table id="cart-table" class="table table-light table-borderless table-hover text-center mb-0">
    <thead class="thead-dark">
        <tr>
            <th>استان</th>
            <th>شهر</th>
            <th>خیابان</th>
        </tr>
    </thead>

    <tbody class="align-middle">

    </tbody>
</table>

<div class="col-md-12">
    <div class="custom-control custom-checkbox">
        <input type="checkbox" class="custom-control-input" id="shipto">
        <label class="custom-control-label" for="shipto"  data-toggle="collapse" data-target="#shipping-address">اضافه کردن آدرس جدید</label>
    </div>
</div>
<form id="add-address" method="post">
    {% csrf_token %}
    <div class="collapse mb-5" id="shipping-address">
        <div class="bg-light p-30">
            <div class="row">
                <div class="col-md-6 form-group">
                    <label>استان</label>
                    <input class="form-control" type="text" name="state">
                </div>
                <div class="col-md-6 form-group">
                    <label>شهر</label>
                    <input class="form-control" type="text" name="city">
                </div>
                <div class="col-md-6 form-group">
                    <label>خیابان</label>
                    <input class="form-control" type="text" name="street">
                </div>
                <div class="p-3 py-5">
                    <div class="row mt-3">
                        <button class="btn btn-primary py-2 px-4" type="submit"> اضافه کردن آدرس</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<script>
$(document).ready(function() {
  $.ajax({
    url: '{% url "customers:address" %}',
    type: 'GET',
    dataType: 'json',
    success: function(data) {
      var addresses = data;
      for (var i = 0; i < addresses.length; i++) {
        var address = addresses[i];
        var row = $('<tr>');
        row.append($('<td>').text(address.state));
        row.append($('<td>').text(address.city));
        row.append($('<td>').text(address.street));
        $('#cart-table tbody').append(row);
      }
    },
  });
  $('#add-address').submit(function(event) {
      event.preventDefault();

      var formData = $(this).serialize();

      $.ajax({
          type: 'POST',
          url: '{% url "customers:address" %}',
          data: formData,
          success: function(response) {
              alert("آدرس با موفقیت ثبت شد!");
          },
      });
  });
});
</script>

shop/customers/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="#">حساب کاربری</a>
                    <span class="breadcrumb-item active">ورود</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Contact Start -->
    <div class="container-fluid">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4" id="check"><span class="bg-secondary pr-3">فرم ورود </span></h2>

        {#add login type#}
        <div id="content" class="row px-xl-5">

        </div>
        <div class="col-md-4">
            <div class="p-3 py-5">
                <hr>
                <div class="row mt-3">
                    <button class="btn btn-primary py-2 px-4" type="submit" id="otp">ورود با کد یکبار مصرف</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Contact End -->

<script>
    $(document).ready(function() {
        $.ajax({
                url: '{% url "customers:login_simple" %}',
                type: 'GET',
                success: function(data) {
                  $("#content").html(data.html);
                },
            });
    });

    $("#otp").click(function() {
        $.ajax({
            url: '{% url "customers:login_otp" %}',
            type: 'GET',
            success: function(data) {
                $("#content").html(data.html);
            },
        });
    });
</script>



{% endblock content %}

shop/customers/templates/login_otp.html
<div class="container-fluid">

        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5">
                <div class="contact-form bg-light p-30">
                    <div id="success"></div>
                    <form method="post" name="sentMessage" id="login-form" novalidate="novalidate">
                        {% csrf_token %}
                        <div class="control-group">
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="شماره همراه"
                                required="required" data-validation-required-message="Please enter your email" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <input type="password" name="password" class="form-control" id="password" placeholder="رمز عبور"
                                required="required" data-validation-required-message="Please enter a subject" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">دریافت کد </button>
                        </div>
                    </form>
                    <form method="post" name="otp-code" id="otp">
                        {% csrf_token %}
                        <div class="control-group">
                            <input type="text" name="code" class="form-control" id="code" placeholder="کد دریافت شده"
                                required="required" data-validation-required-message="Please enter your email" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="sendOtp">ورود</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
</div>

    <script>
        $(document).ready(function() {
          $('#login-form').submit(function(event) {
            event.preventDefault();

            var formData = $(this).serialize();

            $.ajax({
              type: 'POST',
              url: '{% url "customers:login_otp" %}',
              data: formData,
              success: function (response) {
                  console.log('one!!')
                  $('#otp').submit(function (event) {
                      event.preventDefault();
                      var otpData = $(this).serialize();
                      $.ajax({
                          type: 'POST',
                          url: '{% url "customers:verification" %}',
                          data: otpData,
                          success: function (res) {
                              console.log('two!!')
                              if (res.status == 'success') {
                                $.ajax({
                                    type: 'POST',
                                    url: 'http://127.0.0.1:8000/api/token/',
                                    data: formData,
                                    success: function(response) {
                                        console.log('three!!')
                                        var access_token = response.access;
                                        var refresh_token = response.refresh;
                                        document.cookie = "access_token=" + access_token + "; path=/";
                                        document.cookie = "refresh_token=" + refresh_token + "; path=/";
                                        $.ajaxSetup({
                                            headers: {
                                                Authorization: 'Bearer ' + response.access
                                            }
                                        });
                                        $.ajax({
                                            type: 'POST',
                                            url: '{% url "customers:login" %}',
                                            data: formData,
                                            success: function (response) {
                                                console.log('four!!');
                                                // alert("ورود موفقیت آمیز!");
                                                window.location.href = 'http://127.0.0.1:8000/accounts/edit/profile/';
                                            },
                                        });
                                    },
                                });
                              }
                          },
                      });
                  });
              },
            });
          });
        });
    </script>

shop/customers/templates/order.html
<p id="change">
    <table id="cart-table" class="table table-light table-borderless table-hover text-center mb-0">
        <thead class="thead-dark">
            <tr>
                <th>شماره سفارش</th>
                <th>تاریخ</th>
                <th>جزییات</th>
            </tr>
        </thead>

        <tbody class="align-middle">

        </tbody>
    </table>
</p>

<script>
$(document).ready(function() {
  $.ajax({
    url: '{% url "customers:order" %}',
    type: 'GET',
    dataType: 'json',
    success: function(data) {
      var orders = data;
      for (var i = 0; i < orders.length; i++) {
        var order = orders[i];
        var row = $('<tr>');
        var button = $('<button>').text('مشاهده');
        button.data('order-id', order.id);
        button.click(function() {
            var orderId = $(this).data('order-id');
            var url = '{% url "customers:order_detail" 0 %}'.replace('0', orderId);

            $.ajax({
                url: '{% url "customers:order_detail_info" %}',
                type: 'GET',
                success: function (res) {
                    $('#change').html(res.html);

                    sessionStorage.setItem('orderId', orderId);
                    sessionStorage.setItem('url', url);
                },
            });
        });
        row.append($('<td>').text(order.id));
        row.append($('<td>').text(order.jalali_date));
        row.append($('<td>').append(button));
        $('#cart-table tbody').append(row);
      }
    },
  });
});
</script>

shop/customers/templates/profile.html
{% extends 'base.html' %}

{% block content %}


<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg"><span class="font-weight-bold">{{user.fullname}}</span><span class="text-black-50">{{user.email}}</span><span> </span></div>
        </div>
        <div id="content" class="col-md-5 border-right">

        </div>
        <div class="col-md-4">
            <div class="p-3 py-5">
                <div class="row mt-3">
                    <button class="btn btn-primary py-2 px-4" type="submit" id="orders"> تاریخچه سفارش ها</button>
                </div>
                <hr>
                <div class="row mt-3">
                    <button class="btn btn-primary py-2 px-4" type="submit" id="address">آدرس ها</button>
                </div>
                <hr>
                <div class="row mt-3">
                    <button class="btn btn-primary py-2 px-4" type="submit" id="profile">ویرایش پروفایل</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
  $(document).ready(function() {
      var token = getCookie('access_token');
            $.ajaxSetup({
                headers: {
                    Authorization: 'Bearer ' + token
                }
            });
            $.ajax({
                url: '{% url "customers:load" %}',
                type: 'GET',
                success: function(data) {
                  $("#content").html(data.html);
                },
            });

      $("#profile").click(function() {
          var token = getCookie('access_token');
            $.ajaxSetup({
                headers: {
                    Authorization: 'Bearer ' + token
                }
            });
            $.ajax({
                url: '{% url "customers:load" %}',
                type: 'GET',
                success: function(data) {
                  $("#content").html(data.html);
                },
            });
      });

      $("#address").click(function() {
            var token = getCookie('access_token');
            $.ajaxSetup({
                headers: {
                    Authorization: 'Bearer ' + token
                }
            });
            $.ajax({
                url: '{% url "customers:address_info" %}',
                type: 'GET',
                success: function(data) {
                  $("#content").html(data.html);
                },
            });
      });

      $("#orders").click(function() {
            var token = getCookie('access_token');
            $.ajaxSetup({
                headers: {
                    Authorization: 'Bearer ' + token
                }
            });
            $.ajax({
                url: '{% url "customers:order_info" %}',
                type: 'GET',
                success: function(data) {
                  $("#content").html(data.html);
                },
            });
      });
  });
  function getCookie(name) {
  var cookieName = name + "=";
  var cookieArray = document.cookie.split(";");
  for (var i = 0; i < cookieArray.length; i++) {
    var cookie = cookieArray[i];
    while (cookie.charAt(0) === " ") {
      cookie = cookie.substring(1, cookie.length);
    }
    if (cookie.indexOf(cookieName) === 0) {
      return cookie.substring(cookieName.length, cookie.length);
    }
  }
  return null;
}


</script>


{% endblock content %}

shop/customers/templates/verification.html
<div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5">
                <div class="contact-form bg-light p-30">
                    <div id="success"></div>
                    <form method="post" name="sentMessage" id="login-form" novalidate="novalidate">
                        {% csrf_token %}
                        <div class="control-group">
                            <input type="text" name="code" class="form-control" id="code" placeholder="کد دریافت شده"
                                required="required" data-validation-required-message="Please enter your email" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">ورود</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


<script>
    $(document).ready(function() {
        $('#login-form').submit(function(event) {
            event.preventDefault();
            var formData = $(this).serialize();
            $.ajax({
                type: 'POST',
                url: '{% url "customers:verification" %}',
                data: formData,
                success: function (response) {
                    if (response.status == 'success') {
                        $.ajax({
                            type: 'POST',
                            url: '{% url "token_obtain_pair" %}',
                            data: formData,
                            success: function(response) {
                                var access_token = response.access;
                                var refresh_token = response.refresh;
                                document.cookie = "access_token=" + access_token + "; path=/";
                                document.cookie = "refresh_token=" + refresh_token + "; path=/";
                                $.ajaxSetup({
                                    headers: {
                                        Authorization: 'Bearer ' + response.access
                                    }
                                });
                                $.ajax({
                                    type: 'POST',
                                    url: '{% url "customers:login" %}',
                                    data: formData,
                                    success: function (response) {
                                        console.log('ok');
                                        // alert("ورود موفقیت آمیز!");
                                        window.location.href = '{% url "customers:edit_profile" %}';
                                    },
                                });
                            },
                        });
                    }
                },
            });
        });
    });
</script>