shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.show_cart, name='cart'),
    path('detail/', views.CartDetail.as_view(), name='cart_api'),
    path('add/<int:product_id>/', views.AddCartItemView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', views.CartRemoveItemView.as_view(), name='cart_remove'),
    path('checkout/', views.show_checkout, name='checkout'),
    path('final/', views.OrderAPIView.as_view(), name='final'),
    path('paid/', views.CheckOut.as_view(), name='paid')
]

shop/productions/urls.py
from django.urls import path, re_path
from . import views
app_name = 'productions'

urlpatterns = [
    path('', views.LandingPage.as_view(), name='landing_page'),
    path("search/", views.SearchResultsView.as_view(), name="search_results"),
    path('products/', views.ProductList.as_view(), name='product_list'),
    path('categories/', views.CategoryList.as_view(), name='category_list'),
    path("<slug:category_slug>/", views.ProductList.as_view(), name="product_list_by_category"),
    path('<int:id>/<slug:slug>/', views.ProductDetail.as_view(), name='product_detail'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('orders.urls')),
    path('', include('productions.urls', namespace='productions')),
    path('accounts/', include('customers.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/productions/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from core.models import BaseModel


# Create your models here.


class Category(models.Model):
    category_name = models.CharField(verbose_name=_('نام'), max_length=255)
    slug = models.SlugField(max_length=255, editable=False)
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, related_name='child_category', verbose_name=_('دسته بندی والد'))
    photo = models.ImageField(verbose_name=_('عکس'), null=True, blank=True, upload_to='productions/')

    class Meta:
        verbose_name = _('دسته بندی')
        verbose_name_plural = _('دسته بندی ها')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.category_name, allow_unicode=True)
        super().save()

    def get_absolute_url(self):
        return reverse("productions:product_list_by_category", args=[self.slug])

    def __str__(self):
        return self.category_name


class Discount(models.Model):
    type = models.CharField(verbose_name=_('نوع'), max_length=255)
    amount = models.PositiveIntegerField(verbose_name=_('مقدار'))

    class Meta:
        verbose_name = _('تخفیف')
        verbose_name_plural = _('تخفیف ها')

    def __str__(self):
        return str(self.id)


class Product(BaseModel):
    name = models.CharField(verbose_name=_('نام'), max_length=255)
    slug = models.SlugField(max_length=255, editable=False)
    brand = models.CharField(verbose_name=_('برند'), max_length=255)
    specifications = models.CharField(verbose_name=_('مشخصات'), max_length=255)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, verbose_name=_('دسته بندی'))
    price = models.IntegerField(verbose_name=_('قیمت'))
    available = models.BooleanField(verbose_name=_('موجودی'), default=True)
    discount = models.ForeignKey(Discount, null=True, blank=True, on_delete=models.SET_NULL, verbose_name=_('تخفیف'))
    main_image = models.ImageField(verbose_name=_('عکس'), upload_to='productions/')

    class Meta:
        ordering = ('name',)
        verbose_name = _('محصول')
        verbose_name_plural = _('محصولات')

    def get_absolute_url(self):
        return reverse("productions:product_detail", args=[self.id, self.slug])

    def calculate_discount(self):
        if self.discount:
            if self.discount.type == 'percent':
                discount_percent = self.discount.amount
                discount_amount = (self.price * discount_percent) / 100

                return discount_amount

    def calculate_discounted_price(self):
        discounted_price = self.price - self.calculate_discount()
        self.price = discounted_price

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        if self.discount and self.discount.id is None:
            self.discount.save()
        else:
            discount = self.calculate_discount()
            if discount:
                self.calculate_discounted_price()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Image(models.Model):
    name = models.CharField(verbose_name=_('نام'), max_length=255)
    product_id = models.ForeignKey(Product, related_name='image', on_delete=models.CASCADE, verbose_name=_('محصول'))
    photo = models.ImageField(verbose_name=_('عکس'), upload_to='productions/')

    class Meta:
        verbose_name = _('عکس')
        verbose_name_plural = _('عکس ها')

    def __str__(self):
        return self.name

shop/productions/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import ListView, DetailView, TemplateView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import Product, Image, Category
from orders.forms import CartAddProductForm


# Create your views here.


class LandingPage(View):
    def get(self, request):
        last_5_products = Product.objects.order_by('-id')[:4]
        categories = Category.objects.all()
        return render(request, "landing_page.html", {'products': last_5_products})


class CategoryList(ListView):
    model = Category
    template_name = 'category_list.html'
    context_object_name = 'categories'
    paginate_by = 4


# def product_list(request):
#     products = Product.objects.select_related('category').get(id=5)
#     return render(request, 'list.html', {"request": request, "products": products})


class ProductList(ListView):
    model = Product
    template_name = 'list.html'
    context_object_name = 'products'
    paginate_by = 4

    def get_queryset(self):
        queryset = super().get_queryset()
        # queryset = queryset.filter(available=True)
        category_slug = self.kwargs.get('category_slug')

        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            queryset = queryset.filter(category=category)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for product in context['object_list']:
            product.price = '{:20,.0f}'.format(product.price)
        # context['categories'] = Category.objects.all()

        return context


class ProductDetail(DetailView):
    model = Product
    template_name = 'detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_id = self.kwargs.get('id')
        cart_product_form = CartAddProductForm
        context['images'] = Image.objects.filter(product_id=product_id)
        context['product'].price = '{:20,.0f}'.format(context['product'].price)
        context['form'] = cart_product_form
        # context['categories'] = Category.objects.all()
        return context


class SearchResultsView(ListView):
    model = Product
    template_name = 'list.html'
    context_object_name = 'products'

    def get_queryset(self):  # new
        query = self.request.GET.get("q")
        object_list = Product.objects.filter(
            Q(name__icontains=query)
        )
        return object_list

shop/productions/templates/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Carousel Start -->
    <div class="container-fluid mb-3">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <div id="header-carousel" class="carousel slide carousel-fade mb-30 mb-lg-0" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#header-carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#header-carousel" data-slide-to="1"></li>
                        <li data-target="#header-carousel" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item position-relative active" style="height: 430px;">
                            <img class="position-absolute w-100 h-100" src="{% static 'img/carousel-1.jpg' %}" style="object-fit: cover;">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">مردانه</h1>
                                    <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebum magna amet lorem magna erat diam stet. Sadips duo stet amet amet ndiam elitr ipsum diam</p>
                                    <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">خرید</a>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item position-relative" style="height: 430px;">
                            <img class="position-absolute w-100 h-100" src="{% static 'img/carousel-2.jpg' %}" style="object-fit: cover;">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">زنانه</h1>
                                    <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebum magna amet lorem magna erat diam stet. Sadips duo stet amet amet ndiam elitr ipsum diam</p>
                                    <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">خرید</a>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item position-relative" style="height: 430px;">
                            <img class="position-absolute w-100 h-100" src="{% static 'img/kids.jpg' %}" style="object-fit: cover;">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">کودک</h1>
                                    <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebum magna amet lorem magna erat diam stet. Sadips duo stet amet amet ndiam elitr ipsum diam</p>
                                    <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">خرید</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="product-offer mb-30" style="height: 200px;">
                    <img class="img-fluid" src="{% static 'img/offer-1.jpg' %}" alt="">
                    <div class="offer-text">
                        <h6 class="text-white text-uppercase">Save 20%</h6>
                        <h3 class="text-white mb-3">تخفیف ویژه</h3>
                        <a href="" class="btn btn-primary">خرید</a>
                    </div>
                </div>
                <div class="product-offer mb-30" style="height: 200px;">
                    <img class="img-fluid" src="{% static 'img/offer-2.jpg' %}" alt="">
                    <div class="offer-text">
                        <h6 class="text-white text-uppercase">Save 20%</h6>
                        <h3 class="text-white mb-3">تخفیف ویژه</h3>
                        <a href="" class="btn btn-primary">خرید</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Carousel End -->


    <!-- Products Start -->
    <div class="container-fluid pt-5 pb-3">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">دسته بندی</span></h2>


        <div class="row px-xl-5">
            {% for category in categories %}
            <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                <div class="product-item bg-light mb-4">
                    <div class="product-img position-relative overflow-hidden">

                        <img class="img-fluid w-100" src="{{category.photo.url}}" alt="">
                        <div class="product-action">
                            <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-shopping-cart"></i></a>
                            <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                            <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-sync-alt"></i></a>
                            <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-search"></i></a>
                        </div>
                    </div>
                    <div class="text-center py-4">
                        <a class="h6 text-decoration-none text-truncate" href="{{category.get_absolute_url}}">{{category.category_name}}</a>

                        <div class="d-flex align-items-center justify-content-center mb-1">
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small>(99)</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <!-- Add pagination links -->
        <div class="pagination">
            <span class="step-links">

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">بعدی</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">&laquo;آخرین </a>
                {% endif %}

                <span class="current">
                    صفحه {{ page_obj.number }} از {{ page_obj.paginator.num_pages }}
                </span>

                {% if page_obj.has_previous %}
                    <a href="?page=1">&raquo; ابتدا</a>
                    <a href="?page={{ page_obj.previous_page_number }}">قبلی</a>
                {% endif %}
            </span>
        </div>

    </div>
    <!-- Products End -->
{% endblock content %}

shop/productions/templates/detail.html
{% extends 'base.html' %}

{% block content %}
    <!-- Shop Detail Start -->
    <div class="container-fluid pb-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 mb-30">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner bg-light">
                        {% for image in images %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <img class="w-100 h-100" src="{{image.photo.url}}" alt="{{ image.name }}">
                        </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#product-carousel" data-slide="prev">
                        <i class="fa fa-2x fa-angle-left text-dark"></i>
                    </a>
                    <a class="carousel-control-next" href="#product-carousel" data-slide="next">
                        <i class="fa fa-2x fa-angle-right text-dark"></i>
                    </a>
                </div>
            </div>

            <div class="col-lg-7 h-auto mb-30">
                <div class="h-100 bg-light p-30">
                    <h3>{{product.name}}</h3>
                    <div class="d-flex mb-3">
                        <div class="text-primary mr-2">
                            <small class="fas fa-star"></small>
                            <small class="fas fa-star"></small>
                            <small class="fas fa-star"></small>
                            <small class="fas fa-star-half-alt"></small>
                            <small class="far fa-star"></small>
                        </div>
                        <small class="pt-1">(99 Reviews)</small>
                    </div>
                    <h3 class="font-weight-semi-bold mb-4">{{product.price}} تومان</h3>
                    <p class="mb-4">{{product.brand}} برند</p>
                    <p class="mb-4">{{product.specifications}}</p>
                    {% if product.available == True %}
                    <div class="row">
                        <form id="add-cart" method="POST">
                            {% csrf_token %}
                            {{form.as_p}}
                            <input type="submit" value="اضافه کردن به سبد خرید">
                        </form>
                    </div>
                    {% else %}
                    <div class="row">
                         ناموجود
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row px-xl-5">
            <div class="col">
                <div class="bg-light p-30">
                    <div class="nav nav-tabs mb-4">
                        <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-1">Description</a>
                        <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-2">Information</a>
                        <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-3">Reviews (0)</a>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="tab-pane-1">
                            <h4 class="mb-3">Product Description</h4>
                            <p>Eos no lorem eirmod diam diam, eos elitr et gubergren diam sea. Consetetur vero aliquyam invidunt duo dolores et duo sit. Vero diam ea vero et dolore rebum, dolor rebum eirmod consetetur invidunt sed sed et, lorem duo et eos elitr, sadipscing kasd ipsum rebum diam. Dolore diam stet rebum sed tempor kasd eirmod. Takimata kasd ipsum accusam sadipscing, eos dolores sit no ut diam consetetur duo justo est, sit sanctus diam tempor aliquyam eirmod nonumy rebum dolor accusam, ipsum kasd eos consetetur at sit rebum, diam kasd invidunt tempor lorem, ipsum lorem elitr sanctus eirmod takimata dolor ea invidunt.</p>
                            <p>Dolore magna est eirmod sanctus dolor, amet diam et eirmod et ipsum. Amet dolore tempor consetetur sed lorem dolor sit lorem tempor. Gubergren amet amet labore sadipscing clita clita diam clita. Sea amet et sed ipsum lorem elitr et, amet et labore voluptua sit rebum. Ea erat sed et diam takimata sed justo. Magna takimata justo et amet magna et.</p>
                        </div>
                        <div class="tab-pane fade" id="tab-pane-2">
                            <h4 class="mb-3">Additional Information</h4>
                            <p>Eos no lorem eirmod diam diam, eos elitr et gubergren diam sea. Consetetur vero aliquyam invidunt duo dolores et duo sit. Vero diam ea vero et dolore rebum, dolor rebum eirmod consetetur invidunt sed sed et, lorem duo et eos elitr, sadipscing kasd ipsum rebum diam. Dolore diam stet rebum sed tempor kasd eirmod. Takimata kasd ipsum accusam sadipscing, eos dolores sit no ut diam consetetur duo justo est, sit sanctus diam tempor aliquyam eirmod nonumy rebum dolor accusam, ipsum kasd eos consetetur at sit rebum, diam kasd invidunt tempor lorem, ipsum lorem elitr sanctus eirmod takimata dolor ea invidunt.</p>
                            <div class="row">
                                <div class="col-md-6">
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item px-0">
                                            Sit erat duo lorem duo ea consetetur, et eirmod takimata.
                                        </li>
                                        <li class="list-group-item px-0">
                                            Amet kasd gubergren sit sanctus et lorem eos sadipscing at.
                                        </li>
                                        <li class="list-group-item px-0">
                                            Duo amet accusam eirmod nonumy stet et et stet eirmod.
                                        </li>
                                        <li class="list-group-item px-0">
                                            Takimata ea clita labore amet ipsum erat justo voluptua. Nonumy.
                                        </li>
                                      </ul>
                                </div>
                                <div class="col-md-6">
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item px-0">
                                            Sit erat duo lorem duo ea consetetur, et eirmod takimata.
                                        </li>
                                        <li class="list-group-item px-0">
                                            Amet kasd gubergren sit sanctus et lorem eos sadipscing at.
                                        </li>
                                        <li class="list-group-item px-0">
                                            Duo amet accusam eirmod nonumy stet et et stet eirmod.
                                        </li>
                                        <li class="list-group-item px-0">
                                            Takimata ea clita labore amet ipsum erat justo voluptua. Nonumy.
                                        </li>
                                      </ul>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="tab-pane-3">
                            <div class="row">
                                <div class="col-md-6">
                                    <h4 class="mb-4">1 review for "Product Name"</h4>
                                    <div class="media mb-4">
                                        <img src="img/user.jpg" alt="Image" class="img-fluid mr-3 mt-1" style="width: 45px;">
                                        <div class="media-body">
                                            <h6>John Doe<small> - <i>01 Jan 2045</i></small></h6>
                                            <div class="text-primary mb-2">
                                                <i class="fas fa-star"></i>
                                                <i class="fas fa-star"></i>
                                                <i class="fas fa-star"></i>
                                                <i class="fas fa-star-half-alt"></i>
                                                <i class="far fa-star"></i>
                                            </div>
                                            <p>Diam amet duo labore stet elitr ea clita ipsum, tempor labore accusam ipsum et no at. Kasd diam tempor rebum magna dolores sed sed eirmod ipsum.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <h4 class="mb-4">Leave a review</h4>
                                    <small>Your email address will not be published. Required fields are marked *</small>
                                    <div class="d-flex my-3">
                                        <p class="mb-0 mr-2">Your Rating * :</p>
                                        <div class="text-primary">
                                            <i class="far fa-star"></i>
                                            <i class="far fa-star"></i>
                                            <i class="far fa-star"></i>
                                            <i class="far fa-star"></i>
                                            <i class="far fa-star"></i>
                                        </div>
                                    </div>
                                    <form>
                                        <div class="form-group">
                                            <label for="message">Your Review *</label>
                                            <textarea id="message" cols="30" rows="5" class="form-control"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label for="name">Your Name *</label>
                                            <input type="text" class="form-control" id="name">
                                        </div>
                                        <div class="form-group">
                                            <label for="email">Your Email *</label>
                                            <input type="email" class="form-control" id="email">
                                        </div>
                                        <div class="form-group mb-0">
                                            <input type="submit" value="Leave Your Review" class="btn btn-primary px-3">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Shop Detail End -->

<script>
    $(document).ready(function () {
        $('#add-cart').submit(function (event) {
            event.preventDefault();
            // var token = getCookie('access_token');
            var formData = $(this).serialize();

            // $.ajaxSetup({
            //     headers: {
            //         'Authorization': 'Bearer ' + token
            //     }
            // });
            $.ajax({
                type: 'POST',
                url: '{% url "orders:cart_add" product.id %}',
                data: formData,
                success: function (response) {
                    window.location.href = '{% url "orders:cart" %}'
                },
            });
        });
    });
  function getCookie(name) {
  var cookieName = name + "=";
  var cookieArray = document.cookie.split(";");
  for (var i = 0; i < cookieArray.length; i++) {
    var cookie = cookieArray[i];
    while (cookie.charAt(0) === " ") {
      cookie = cookie.substring(1, cookie.length);
    }
    if (cookie.indexOf(cookieName) === 0) {
      return cookie.substring(cookieName.length, cookie.length);
    }
  }
  return null;
}

</script>
{% endblock content %}
