shop/customers/urls.py
from django.urls import path
from . import api
from . import views

app_name = 'customers'

urlpatterns = [
      path('edit/profile/', views.show_profile, name='edit_profile'),
      path('load/', views.ProfileInfo.as_view(), name='load'),
      path('profile/', api.Profile.as_view(), name='profile'),
      path('api/login/', api.LoginAPIView.as_view(), name='login'),
      path('login-simple/', views.LoginSimple.as_view(), name='login_simple'),
      path('login-otp/', api.LoginOtp.as_view(), name='login_otp'),
      path('verification/', api.Verification.as_view(), name='verification'),
      path('api/register/', api.RegisterApi.as_view(), name="register"),
      path('logout/', api.Logout.as_view(), name='logout'),
      path('address/', api.AddressApi.as_view(), name='address'),
      path('address-info/', views.AddressInfo.as_view(), name='address_info'),
      path('order/', api.OrderAPI.as_view(), name='order'),
      path('order-info/', views.OrderInfo.as_view(), name='order_info'),
      path('order/<int:pk>/', api.OrderDetail.as_view(), name='order_detail'),
      path('order-detail/', views.OrderDetailInfo.as_view(), name='order_detail_info'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.show_cart, name='cart'),
    path('detail/', views.CartDetail.as_view(), name='cart_api'),
    path('add/<int:product_id>/', views.AddCartItemView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', views.CartRemoveItemView.as_view(), name='cart_remove'),
    path('checkout/', views.show_checkout, name='checkout'),
    path('final/', views.OrderAPIView.as_view(), name='final'),
    path('paid/', views.CheckOut.as_view(), name='paid')
]

shop/productions/urls.py
from django.urls import path, re_path
from . import views
app_name = 'productions'

urlpatterns = [
    path('', views.LandingPage.as_view(), name='landing_page'),
    path("search/", views.SearchResultsView.as_view(), name="search_results"),
    path('products/', views.ProductList.as_view(), name='product_list'),
    path('categories/', views.CategoryList.as_view(), name='category_list'),
    path("<slug:category_slug>/", views.ProductList.as_view(), name="product_list_by_category"),
    path('<int:id>/<slug:slug>/', views.ProductDetail.as_view(), name='product_detail'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('orders.urls')),
    path('', include('productions.urls', namespace='productions')),
    path('accounts/', include('customers.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/templates/partials/footer.html
{% load static %}
<!-- Footer Start -->
    <div class="container-fluid bg-dark text-secondary mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <h5 class="text-secondary text-uppercase mb-4">آدرس</h5>
                <p class="mb-4">No dolore ipsum accusam no lorem. Invidunt sed clita kasd clita et et dolor sed dolor. Rebum tempor no vero est magna amet no</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Quick Shop</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">My Account</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-secondary" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Newsletter</h5>
                        <p>Duo stet tempor ipsum sit amet magna ipsum tempor est</p>
                        <form action="">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Your Email Address">
                                <div class="input-group-append">
                                    <button class="btn btn-primary">Sign Up</button>
                                </div>
                            </div>
                        </form>
                        <h6 class="text-secondary text-uppercase mt-4 mb-3">Follow Us</h6>
                        <div class="d-flex">
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-primary btn-square mr-2" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-secondary">
                    &copy; <a class="text-primary" href="#">Domain</a>. All Rights Reserved. Designed
                    by
                    <a class="text-primary" href="https://htmlcodex.com">HTML Codex</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="{% static 'img/payments.png' %}" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->

shop/templates/partials/header.html
{% load static %}
<!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-1 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center h-100">
                    <a class="text-body mr-3" href="">درباره</a>
                    <a class="text-body mr-3" href="">ارتباط</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">حساب کاربری</button>
                        <div class="dropdown-menu dropdown-menu-right">
                            {% if request.COOKIES.access_token %}
                                <a href="{% url 'customers:edit_profile' %}"><button class="dropdown-item" type="button">پروفایل</button></a>
                                <a href="#" id="logout-button"><button class="dropdown-item" type="button">خروج</button></a>
                            {% else %}
                                <a href="{% url 'customers:register' %}"><button class="dropdown-item" type="button">ثبت نام</button></a>
                                <a href="{% url 'customers:login' %}"><button class="dropdown-item" type="button">ورود</button></a>
                            {% endif %}
                        </div>
                    </div>

                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">فارسی</button>
                        <div class="dropdown-menu dropdown-menu-right">
                            <button class="dropdown-item" type="button">ENGLISH</button>
                        </div>
                    </div>
                </div>
                <div class="d-inline-flex align-items-center d-block d-lg-none">
                    <a href="" class="btn px-0 ml-2">
                        <i class="fas fa-heart text-dark"></i>
                        <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                    </a>
                    <a href="" class="btn px-0 ml-2">
                        <i class="fas fa-shopping-cart text-dark"></i>
                        <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
            <div class="col-lg-4">
                <a href="" class="text-decoration-none">
                    <span class="h1 text-uppercase text-primary bg-dark px-2">فروشگاه</span>
                    <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">SHOP</span>
                </a>
            </div>
            <div class="col-lg-4 col-6 text-left">
                <form action="{% url 'productions:search_results' %}" method="get">
                    <div class="input-group">
                        <input name="q" type="text" class="form-control" placeholder="محصول مورد نظر">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-4 col-6 text-right">
                <p class="m-0">ارتباط</p>
                <h5 class="m-0">09190000000</h5>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
<!-- Navbar Start -->
    <div class="container-fluid bg-dark mb-30">
        <div class="row px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                    <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>دسته بندی محصولات</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                    <div class="navbar-nav w-100">
                        {% for category in categories %}
                            <a href="{% url 'productions:product_list_by_category' category.slug %}" class="nav-item nav-link">{{category.category_name}}</a>
                        {% endfor %}
                    </div>
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                    <a href="" class="text-decoration-none d-block d-lg-none">
                        <span class="h1 text-uppercase text-dark bg-light px-2">Multi</span>
                        <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            <a href="{% url 'productions:landing_page' %}" class="nav-item nav-link active">صفحه اصلی</a>
                            <a href="{% url 'productions:product_list' %}" class="nav-item nav-link">محصولات</a>
                            <a href="{% url 'productions:category_list' %}" class="nav-item nav-link">دسته بندی</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">صفحه ها <i class="fa fa-angle-down mt-1"></i></a>
                                <div class="dropdown-menu bg-primary rounded-0 border-0 m-0">
                                    <a href="{% url 'orders:cart' %}" class="dropdown-item">سبد خرید</a>
                                    <a href="{% url 'orders:checkout' %}" class="dropdown-item">پرداخت</a>
                                </div>
                            </div>
                        </div>
                        <div class="navbar-nav ml-auto py-0 d-none d-lg-block text-left">
<!--                            <a href="" class="btn px-0">-->
<!--                                <i class="fas fa-heart text-primary"></i>-->
<!--                                <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">0</span>-->
<!--                            </a>-->
                            <a href="{% url 'orders:cart' %}" class="btn px-0 ml-3">
                                <i class="fas fa-shopping-cart text-primary"></i>
                                <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">0</span>
                            </a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>

<script>
  $(document).ready(function() {
    $('#logout-button').click(function(event) {
        event.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "customers:logout" %}',
            success: function(response) {
            alert("خروج موفقیت آمیز");
            window.location.href = 'http://127.0.0.1:8000/'
        },
    });
  });
});

</script>
    <!-- Navbar End -->